### ISSUE TITLE
Switch from objects { x: , y: , z: } to arrays [x, y, z] for wider npm compatibility

### ISSUE THREAD

**Issue by vorg** [vorg/pex-rfc#2]

**Comment by szymonkaliski** [comment]
This change looks huge, and possibly breaking a lot of things, do you have some ideas as to how to implement it most painlessly?

**Comment by dawidgorny** [comment]
You can already use `Vec3.fromArray( [x,y,z] )` then we can simply add `vec.toArray()`. Is it satisfying?

**Comment by vorg** [comment]
I think is a bigger question that would go into every part of the library
e.g.

```
var ray = new Ray([0,0,0], [0,1,0]);
//vs
var ray = new Ray(new Vec3(0,0,0), new Vec3(0,1,0));
```

```
mesh.position = [0, 0, 10]
//vs
mesh.position = new Vec3(0, 0, 10);
```

etc..

On Tue, May 12, 2015 at 3:42 PM, Dawid Górny <notifications@github.com>
wrote:

> You can already use Vec3.fromArray( [x,y,z] ) then we can simply add
> vec.toArray(). Is it satisfying?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/vorg/pex-rfc/issues/2#issuecomment-101305044>.
>



-- 
Marcin Ignac
http://marcinignac.com
@marcinignac

**Comment by vorg** [comment]
I think it's a bigger question that would go into every part of the library
e.g.

``` javascript
var ray = new Ray([0,0,0], [0,1,0]);
mesh.position = [0, 0, 10]
```

vs

``` javascript
var ray = new Ray(new Vec3(0,0,0), new Vec3(0,1,0));
mesh.position = new Vec3(0, 0, 10);
```

**Comment by dawidgorny** [comment]
I kind of like this idea. How vectors operations would look like? `dot([0.5,0.5,0], [0,1,0])`? `translate(mesh.position, [1,0.5,0])`?

**Comment by vorg** [comment]
Yes, it would be something like

``` javascript
var position = [0,0,0];
var velocity = [0,1,0];
Vec3.add(position, velocity); //modifies position
```

Or in case of `gl-matrix` and `gl-vec3` where first parameter is `out` aka `result`:

``` javascript
//here we also modify position but we don't have to
vec3.add(position, position, velocity); 
vec3.add(finalPos, position, velocity); 
```

So there are three possible approaches

``` javascript
vec3.add(a, b); //returns new array, lots of garbage collection
vec3.add(a, b); //modifies a
vec3.add(out, a, b); //modifies out
```

`gl-matrix` was using style 2 with optional 3 but now they moved to `out` required every time which feels a bit awkward when you need to do `vec3.normalize(n, n)` no idea how to read it :/

Having everything as functions allows you to do

``` javascript
var sub = require('gl-vec3/sub');
var normalize = require('gl-vec3/normalize');
var n = [0, 0, 0];
sub(n, a, b);
normalize(n, n);
```

In `pex` this could be

``` javascript
var Vec3 = require('pex-geom').Vec3;
var n = Vec3.clone(a);
Vec3.sub(n, b);
Vec3.normalize(n);
```

or

``` javascript
var Vec3 = require('pex-geom').Vec3;
var clone = Vec3.clone;
var sub = Vec3.sub;
var normalize = Vec3.normalize;
var n = clone(a);
sub(n, b);
normalize(n);
```

or

``` javascript
var n = normalize(sub(clone(a), b));
```

You could also ditch classes and have `pex-geom/add3` and `pex-geom/normalize3`

``` javascript
var copy3 = require('pex-geom/copy3');
var sub3 = require('pex-geom/sub3');
var normalize3 = require('pex-geom/normalize3');
var n = [0, 0, 0];
copy3(n, a);
sub3(n, b);
normalize3(n);
```

**Comment by vorg** [comment]
Examples of arrays used in practice

https://github.com/mattdesl/torus-mesh/blob/master/index.js#L38
https://github.com/substack/ray-triangle-intersection/blob/master/index.js

The short story is, i many many cases you don't care about the class:
- window.getSize() -> returns [width, height]
- mesh.position = [0, 0, 5]
- mesh.material.uniforms.scale = [0.5, 0.5];
- texCoords = [[0,0], [1,0], [1,1], [0,1]]

In others you use only few functions that you can import by name
- e.g. you move position by velocity -> require `add3`
- you build and normalize normals -> require `cross3` and `normalize3`

etc.

**Comment by nkint** [comment]
Hi, I'm sporadically follow pex development.
This issue seems to be resolved looking at [Vec2D module](https://github.com/pex-gl/pex-math/blob/master/Vec2.js). Seems to me that this ensures certain level of compatibility with stack.gl.. right? 

Is this repository still updated anyhow?

**Comment by vorg** [comment]
Done

**Comment by nkint** [comment]
🎉
